[package]
name = "findb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
env_logger = "0.10.0"
log = "0.4.19"
ordered-float = "3.7.0"
peg = "0.8.1"
prettytable-rs = "0.10.0"
serde = "1.0.171"
serde_json = "1.0.102"
time = { version = "0.3.23", features = ["std"] }
tokio = { version = "1.30.0", features = ["full"] }
uuid = { version = "1.4.0", features = ["v4"] }
